project_id = "ndzuvmvvqotzxdlljope"

[auth]
site_url = "https://muberapp.vercel.app"
additional_redirect_urls = [
  "https://muberapp.vercel.app/auth/callback",
  "https://muberapp.vercel.app/auth/reset",
  "https://muber-8pifn1mvx-manuel-rodriguezs-projects-f5946c44.vercel.app/auth/callback",
  "https://muber-8pifn1mvx-manuel-rodriguezs-projects-f5946c44.vercel.app/auth/reset",
  "http://localhost:3000/auth/callback",
  "http://localhost:3000/auth/reset",
]

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8
