-- MUBER Phase 1 schema DRAFT — DO NOT DEPLOY until auth roles and ownership are confirmed.
-- Assumes auth.users exists. Media is private and accessed through short-lived signed URLs.
create extension if not exists pgcrypto;
create type public.app_role as enum ('customer','provider_owner','provider_staff','crew','dispatcher','admin');
create type public.job_service as enum ('move','remove');
create type public.job_status as enum ('draft','requested','reviewing','quoted','accepted','assigned','en_route','in_progress','completed','cancelled','disputed');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, role app_role not null default 'customer', full_name text, phone text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, kind text not null check(kind in ('provider','business','muber')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.organization_members (organization_id uuid references public.organizations on delete cascade, profile_id uuid references public.profiles on delete cascade, role app_role not null, created_at timestamptz not null default now(), primary key(organization_id,profile_id));
create table public.provider_companies (id uuid primary key default gen_random_uuid(), organization_id uuid not null unique references public.organizations on delete restrict, legal_name text not null, status text not null default 'pending' check(status in ('pending','reviewing','approved','suspended')), service_area jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.provider_credentials (id uuid primary key default gen_random_uuid(), provider_company_id uuid not null references public.provider_companies on delete cascade, credential_type text not null, identifier text, expires_at date, verification_status text not null default 'pending', private_storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.vehicles (id uuid primary key default gen_random_uuid(), provider_company_id uuid not null references public.provider_companies on delete cascade, label text not null, vehicle_type text not null, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.crews (id uuid primary key default gen_random_uuid(), provider_company_id uuid not null references public.provider_companies on delete cascade, name text not null, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.crew_members (crew_id uuid references public.crews on delete cascade, profile_id uuid references public.profiles on delete cascade, created_at timestamptz not null default now(), primary key(crew_id,profile_id));
create table public.customers (id uuid primary key default gen_random_uuid(), profile_id uuid unique references public.profiles on delete set null, organization_id uuid references public.organizations on delete set null, email text not null, full_name text not null, phone text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.addresses (id uuid primary key default gen_random_uuid(), customer_id uuid references public.customers on delete cascade, line1 text not null, line2 text, city text not null, region text not null, postal_code text not null, access_notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.jobs (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers on delete restrict, service job_service not null, status job_status not null default 'draft', preferred_start timestamptz, preferred_end timestamptz, description text not null default '', accepted_quote_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.job_stops (id uuid primary key default gen_random_uuid(), job_id uuid not null references public.jobs on delete cascade, address_id uuid not null references public.addresses on delete restrict, stop_order integer not null check(stop_order>=0), stop_type text not null check(stop_type in ('pickup','destination','service','additional')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(job_id,stop_order));
create table public.job_items (id uuid primary key default gen_random_uuid(), job_id uuid not null references public.jobs on delete cascade, category text not null, description text, quantity integer check(quantity is null or quantity>0), heavy boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.job_media (id uuid primary key default gen_random_uuid(), job_id uuid not null references public.jobs on delete cascade, uploaded_by uuid not null references public.profiles on delete restrict, storage_path text not null unique, mime_type text not null check(mime_type in ('image/jpeg','image/png','image/webp','image/heic')), byte_size bigint not null check(byte_size between 1 and 10485760), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.quotes (id uuid primary key default gen_random_uuid(), job_id uuid not null references public.jobs on delete cascade, provider_company_id uuid references public.provider_companies on delete restrict, amount_cents integer not null check(amount_cents>=0), currency text not null default 'usd' check(currency='usd'), status text not null check(status in ('draft','offered','accepted','declined','expired')), expires_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.jobs add constraint jobs_accepted_quote_fk foreign key(accepted_quote_id) references public.quotes(id) on delete set null;
create table public.assignments (id uuid primary key default gen_random_uuid(), job_id uuid not null references public.jobs on delete cascade, provider_company_id uuid not null references public.provider_companies on delete restrict, crew_id uuid references public.crews on delete set null, vehicle_id uuid references public.vehicles on delete set null, status text not null default 'offered', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.job_status_events (id uuid primary key default gen_random_uuid(), job_id uuid not null references public.jobs on delete cascade, status job_status not null, actor_id uuid references public.profiles on delete restrict, occurred_at timestamptz not null default now(), note text, metadata jsonb not null default '{}');
create table public.change_orders (id uuid primary key default gen_random_uuid(), job_id uuid not null references public.jobs on delete cascade, requested_by uuid not null references public.profiles on delete restrict, description text not null, amount_delta_cents integer not null, status text not null check(status in ('pending','approved','declined')), decided_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.completion_records (id uuid primary key default gen_random_uuid(), job_id uuid not null unique references public.jobs on delete restrict, completed_by uuid not null references public.profiles on delete restrict, customer_confirmed_at timestamptz, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.reviews (id uuid primary key default gen_random_uuid(), job_id uuid not null unique references public.jobs on delete restrict, customer_id uuid not null references public.customers on delete restrict, provider_company_id uuid not null references public.provider_companies on delete restrict, rating integer not null check(rating between 1 and 5), body text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.audit_events (id uuid primary key default gen_random_uuid(), actor_id uuid references public.profiles on delete set null, action text not null, entity_type text not null, entity_id uuid, metadata jsonb not null default '{}', occurred_at timestamptz not null default now());

create function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
do $$ declare t text; begin foreach t in array array['profiles','organizations','provider_companies','provider_credentials','vehicles','crews','customers','addresses','jobs','job_stops','job_items','job_media','quotes','assignments','change_orders','completion_records','reviews'] loop execute format('create trigger set_%I_updated before update on public.%I for each row execute function public.set_updated_at()',t,t); end loop; end $$;
create function public.prevent_event_mutation() returns trigger language plpgsql as $$ begin raise exception 'event history is immutable'; end $$;
create trigger immutable_job_status_events before update or delete on public.job_status_events for each row execute function public.prevent_event_mutation();
create trigger immutable_audit_events before update or delete on public.audit_events for each row execute function public.prevent_event_mutation();

-- Default deny: enabling RLS with no broad policies prevents accidental exposure.
do $$ declare t text; begin foreach t in array array['profiles','organizations','organization_members','provider_companies','provider_credentials','vehicles','crews','crew_members','customers','addresses','jobs','job_stops','job_items','job_media','quotes','assignments','job_status_events','change_orders','completion_records','reviews','audit_events'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy "profiles read self" on public.profiles for select using (id=auth.uid());
-- Profile writes intentionally have no direct client policy. Customer-editable fields
-- are changed through narrowly scoped functions so role can never be client-controlled.
-- SECURITY DECISIONS REQUIRED BEFORE DEPLOYMENT:
-- 1. Store effective roles in profiles vs JWT app_metadata, and who may change them.
-- 2. Whether business accounts can create jobs for multiple contacts/locations.
-- 3. Exact dispatcher/admin claims and break-glass audit requirements.
-- 4. Provider visibility before assignment and customer/provider chat retention.
-- Add narrow ownership/membership policies only after those decisions; use service-role
-- functions exclusively on trusted servers, never in the browser.
