create type public.provider_application_status as enum ('draft','submitted','under_review','information_requested','approved','rejected','withdrawn','suspended');
create type public.credential_status as enum ('missing','submitted','under_review','verified','rejected','expiring','expired','suspended');
create type public.quote_status as enum ('draft','ready_for_review','sent','viewed','accepted','declined','expired','superseded','cancelled');
create type public.offer_status as enum ('draft','sent','viewed','accepted','declined','expired','withdrawn','superseded');

create table public.provider_applications(id uuid primary key default gen_random_uuid(), applicant_id uuid not null references public.profiles on delete restrict, legal_name text not null, dba_name text, business_email text not null, business_phone text not null, contact_name text not null, business_address jsonb not null, service_categories text[] not null, service_territory text not null, years_in_business int check(years_in_business>=0), website text, moving_services text[], removal_services text[], vehicle_types text[], crew_capacity int check(crew_capacity>0), operating_hours jsonb not null default '{}', same_day_available boolean not null default false, commercial_auto_status text, liability_status text, cargo_status text, ca_mover_permit_status text, disposal_capability boolean not null default false, background_consent boolean not null default false, agreement_accepted boolean not null default false, notes text, status provider_application_status not null default 'draft', internal_reason text, submitted_at timestamptz, decided_at timestamptz, decided_by uuid references public.profiles, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index one_open_provider_application on public.provider_applications(applicant_id) where status not in ('rejected','withdrawn');
create index provider_applications_status_idx on public.provider_applications(status,created_at);

alter table public.provider_credentials add column credential_number text, add column issuing_authority text, add column issued_at date, add column submitted_at timestamptz, add column verified_at timestamptz, add column reviewer_id uuid references public.profiles, add column rejection_reason text;
alter table public.vehicles add column make text, add column model text, add column model_year int check(model_year between 1900 and 2200), add column plate_metadata text, add column capacity_class text, add column cargo_dimensions text, add column weight_capability text, add column lift_gate boolean not null default false, add column ramp boolean not null default false, add column enclosed boolean, add column service_categories text[] not null default '{}', add column insurance_eligible boolean not null default false, add column internal_notes text;
alter table public.crews add column crew_size int not null default 1 check(crew_size>0), add column capabilities text[] not null default '{}', add column heavy_item_capable boolean not null default false, add column moving_eligible boolean not null default false, add column removal_eligible boolean not null default false, add column availability jsonb not null default '{}';

create table public.internal_job_reviews(id uuid primary key default gen_random_uuid(),job_id uuid not null unique references public.jobs on delete cascade,complexity text,risk_flags text[] not null default '{}',required_crew_size int check(required_crew_size>0),required_vehicle_class text,credential_requirements text[] not null default '{}',internal_notes text,reviewed_by uuid references public.profiles,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.quote_versions(id uuid primary key default gen_random_uuid(),job_id uuid not null references public.jobs on delete cascade,version int not null check(version>0),service_subtotal_cents int not null check(service_subtotal_cents>=0),disposal_cents int not null default 0 check(disposal_cents>=0),travel_cents int not null default 0 check(travel_cents>=0),other_cents int not null default 0 check(other_cents>=0),total_cents int generated always as(service_subtotal_cents+disposal_cents+travel_cents+other_cents) stored,currency text not null default 'usd' check(currency='usd'),customer_scope text not null,internal_notes text,estimated_provider_compensation_cents int check(estimated_provider_compensation_cents>=0),expires_at timestamptz,status quote_status not null default 'draft',created_by uuid not null references public.profiles,accepted_by uuid references public.profiles,accepted_at timestamptz,created_at timestamptz not null default now(),unique(job_id,version));
create table public.provider_offers(id uuid primary key default gen_random_uuid(),job_id uuid not null references public.jobs on delete cascade,provider_company_id uuid not null references public.provider_companies on delete restrict,quote_version_id uuid references public.quote_versions on delete restrict,approximate_pickup_area text,approximate_destination_area text,scope text not null,required_vehicle text,required_crew_size int,estimated_duration_minutes int,compensation_cents int not null check(compensation_cents>=0),currency text not null default 'usd' check(currency='usd'),expires_at timestamptz not null,status offer_status not null default 'draft',decline_reason text,created_by uuid not null references public.profiles,responded_by uuid references public.profiles,responded_at timestamptz,created_at timestamptz not null default now());
create index provider_offers_company_status_idx on public.provider_offers(provider_company_id,status);
alter table public.assignments add column assigned_by uuid references public.profiles, add column assigned_at timestamptz, add column provider_accepted_at timestamptz, add column crew_confirmed_at timestamptz, add column scheduled_start timestamptz, add column scheduled_end timestamptz, add column reassignment_reason text, add column cancellation_reason text;

alter table public.provider_applications enable row level security; alter table public.internal_job_reviews enable row level security; alter table public.quote_versions enable row level security; alter table public.provider_offers enable row level security;
create policy "applicants read own applications" on public.provider_applications for select to authenticated using(applicant_id=auth.uid());
create policy "applicants create drafts" on public.provider_applications for insert to authenticated with check(applicant_id=auth.uid() and status='draft');
create policy "applicants edit drafts" on public.provider_applications for update to authenticated using(applicant_id=auth.uid() and status in('draft','information_requested')) with check(applicant_id=auth.uid() and status in('draft','submitted'));
create policy "provider members read own offers" on public.provider_offers for select to authenticated using(provider_company_id in(select pc.id from public.provider_companies pc join public.organization_members om on om.organization_id=pc.organization_id where om.profile_id=auth.uid()));
create policy "customers read sent quotes" on public.quote_versions for select to authenticated using(status in('sent','viewed','accepted','declined','expired','superseded') and public.owns_job(job_id));

create or replace function public.submit_provider_application(p_id uuid) returns void language plpgsql security definer set search_path=public as $$ begin update public.provider_applications set status='submitted',submitted_at=now() where id=p_id and applicant_id=auth.uid() and status in('draft','information_requested') and background_consent and agreement_accepted; if not found then raise exception 'application cannot be submitted'; end if; insert into public.audit_events(actor_id,action,entity_type,entity_id) values(auth.uid(),'provider_application.submitted','provider_application',p_id); end $$;
revoke all on function public.submit_provider_application(uuid) from public; grant execute on function public.submit_provider_application(uuid) to authenticated;

create or replace function public.assign_privileged_role(p_user uuid,p_role public.app_role,p_reason text) returns void language plpgsql security definer set search_path=public as $$ declare v_role public.app_role; begin select role into v_role from public.profiles where id=auth.uid(); if v_role<>'super_admin' then raise exception 'forbidden'; end if; if p_role not in('dispatcher','compliance_admin','finance_admin','super_admin') or length(trim(p_reason))<10 then raise exception 'invalid assignment'; end if; update public.profiles set role=p_role where id=p_user; insert into public.audit_events(actor_id,action,entity_type,entity_id,metadata) values(auth.uid(),'role.assigned','profile',p_user,jsonb_build_object('role',p_role,'reason',p_reason)); end $$;
revoke all on function public.assign_privileged_role(uuid,public.app_role,text) from public; grant execute on function public.assign_privileged_role(uuid,public.app_role,text) to authenticated;

-- First super-admin bootstrap is intentionally not automated. Run one reviewed SQL
-- transaction with an explicit existing auth user UUID and matching audit event.
