create or replace function public.crew_has_assigned_job(p_job uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.assignments a join public.crew_members cm on cm.crew_id=a.crew_id where a.job_id=p_job and cm.profile_id=auth.uid() and a.status in ('crew_assigned','crew_confirmed','ready','en_route','arrived','in_progress','completion_review','completed')) $$;
create or replace function public.revise_completion(p_assignment uuid,p_payload jsonb,p_request_id uuid) returns uuid language plpgsql security definer set search_path=public as $$
declare v_a public.assignments%rowtype;v_previous public.completion_submissions%rowtype;v_id uuid;v_version int;
begin
 select entity_id into v_id from public.audit_events where actor_id=auth.uid() and action='completion.revised' and request_id=p_request_id;if v_id is not null then return v_id;end if;
 if not public.has_any_role(array['crew_lead']::public.app_role[]) then raise exception 'crew lead required';end if;
 select * into v_a from public.assignments where id=p_assignment for update;if not found or v_a.status<>'completion_review' or not exists(select 1 from public.crew_members where crew_id=v_a.crew_id and profile_id=auth.uid()) then raise exception 'assignment not available';end if;
 select * into v_previous from public.completion_submissions where assignment_id=p_assignment order by version desc limit 1 for update;if not found or v_previous.status not in ('more_information_requested','returned_to_provider') then raise exception 'revision was not requested';end if;
 if length(trim(coalesce(p_payload->>'work_summary',''))) not between 20 and 5000 or length(trim(coalesce(p_payload->>'items_summary',''))) not between 10 and 5000 or length(trim(coalesce(p_payload->>'customer_summary',''))) not between 20 and 2000 then raise exception 'completion summary is incomplete';end if;v_version:=v_previous.version+1;
 insert into public.completion_submissions(job_id,assignment_id,provider_company_id,crew_id,submitted_by,version,completion_at,completion_notes,work_summary,items_summary,customer_summary,disposal_destination,donation_destination,disposal_receipt_status,damage_declared,incident_declared,missing_item_declared,access_issue_declared,additional_scope_declared,customer_present,request_id) values(v_a.job_id,v_a.id,v_a.provider_company_id,v_a.crew_id,auth.uid(),v_version,now(),trim(coalesce(p_payload->>'completion_notes','')),trim(p_payload->>'work_summary'),trim(p_payload->>'items_summary'),trim(p_payload->>'customer_summary'),nullif(trim(p_payload->>'disposal_destination'),''),nullif(trim(p_payload->>'donation_destination'),''),coalesce(nullif(p_payload->>'disposal_receipt_status',''),'not_applicable'),coalesce((p_payload->>'damage_declared')::boolean,false),coalesce((p_payload->>'incident_declared')::boolean,false),coalesce((p_payload->>'missing_item_declared')::boolean,false),coalesce((p_payload->>'access_issue_declared')::boolean,false),coalesce((p_payload->>'additional_scope_declared')::boolean,false),nullif(p_payload->>'customer_present','')::boolean,p_request_id) returning id into v_id;
 insert into public.audit_events(actor_id,action,entity_type,entity_id,metadata,request_id) values(auth.uid(),'completion.revised','completion_submission',v_id,jsonb_build_object('job_id',v_a.job_id,'assignment_id',v_a.id,'version',v_version,'previous_submission_id',v_previous.id),p_request_id);return v_id;
end $$;
revoke all on function public.revise_completion(uuid,jsonb,uuid) from public;grant execute on function public.revise_completion(uuid,jsonb,uuid) to authenticated;
